### ISSUE TITLE
feat: integrate floor prices of 20 most popular NFT collections from OpenSea

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-custom-urls-manifest-updater#16]
- Understand the redstone-custom-urls-manifest-updater code
- Go through the OpenSea API docs: https://docs.opensea.io/reference/api-overview
- Prepare a node.js script which automatically register data feeds from open-sea using cutom-urls metchanism
  - The script should interact with the [custom-urls-manifest-updater api](https://custom-urls-manifest-updater.redstone.finance/api)
  - The script should register corresponding urls (e.g. https://api.opensea.io/api/v1/collection/doodles-official/stats) and jsonpaths (e.g. `$.stats.floor_price`)
- Update [redstone-app](https://github.com/redstone-finance/redstone-app) to display registered floor price values for NFTs in a separate tab

**Comment by skromez** [comment]
some collections don't have ```floor_price``` - https://api.opensea.io/api/v1/collection/cryptopunks/stats
because of that custom-urls throwing a validation error, should we use ```average_price``` instead of ```floor_price``` if it's null? @hatskier

**Comment by skromez** [comment]
Also, there's no public Opensea API that returns a list of the most popular collections. They have a GraphQL API which they're using internally. 
We can either 
- Just have an array of the 20 most popular slugs in the script and use them
- Use Opensea Scraper which uses a puppeteer to scrape the information about the most popular collections.

I've implemented the second approach in this PR
